### ISSUE TITLE
The formatKotlin is not compatible with ktlintCheck 

### ISSUE THREAD

**Issue by nechkin** [hovinen/kotlin-auto-formatter#1]
The formatter’s output causes ktlint to complain, where it did not complain previously.

NB! Created a single ticket for the problems encountered. Let me know if it is wrong, will create separate tickets for each problem.

1. 
Code before the formatter:

```
requeueService.invokeAction(
    onError = { _, _ -> },
)
```

Code after the formatter:

```
requeueService.invokeAction(
    onError = { _, _ ->},
)
```

Error from ktlintCheck after the formatKotlin:

Missing spacing after "->"
Missing spacing before "}"

2. 
Code before the formatter:

```
/**
 * @param accessToken the token that grant access and identify the user.
 */
constructor(
    accessToken: String
) : this(accessToken)
```

Code after the formatter:

```
/**
 * @param accessToken the token that grant access and identify the user.
 */ constructor(
    accessToken: String
) : this(accessToken)
```

Error from ktlintCheck after the formatKotlin:

Unexpected indentation (expected 9, actual 8)

**Comment by hovinen** [comment]
Thanks for reporting this. I've pushed a fix for each issue and will publish version 0.4.12 shortly.
