### ISSUE TITLE
./gradlew formatKotlin produces output that appears to conflict with ktlint

### ISSUE THREAD

**Issue by danielocallaghan** [hovinen/kotlin-auto-formatter#21]
with the gradle dependency specified as:
``` 
id("tech.formatter-kt.formatter") version "0.7.7"
```
Given the following input (abbreviated):
```
internal class AttributeExtensionsTest {

    @TestFactory
    fun `isAbsencePlannedDays should return true for absence planned days attribute and false for any other attribute`() =
        listOf(
            "absence_1:planned_days" to true,
            "absence_12345:planned_days" to true,
            "absence_5:taken_days" to false,
            "absence_123:contractual_hours" to false,
            "first_name" to false,
            "contractual_hours" to false,
            "attendance_contractual_target_hours" to false
        )
            .map { (attribute, result) ->
                DynamicTest.dynamicTest("$attribute is an absence planned days attribute: $result") {
                    attribute.isAbsencePlannedDays() `should be equal to` result
                }            
}
```
after running: `./gradlew formatKotlin`

produces:
```
internal class AttributeExtensionsTest {

    @TestFactory
    fun `isAbsencePlannedDays should return true for absence planned days attribute and false for any other attribute`() =
        listOf(
            "absence_1:planned_days" to true,
            "absence_12345:planned_days" to true,
            "absence_5:taken_days" to false,
            "absence_123:contractual_hours" to false,
            "first_name" to false,
            "contractual_hours" to false,
            "attendance_contractual_target_hours" to false
        )
            .map { (attribute, result) ->
                DynamicTest.dynamicTest("$attribute is an absence planned days attribute: $result")
                    { attribute.isAbsencePlannedDays() `should be equal to` result }
            
}
```

which leads to a ktlint error:
```
> Task :ktlintMainSourceSetCheck
.../extensions/AttributeExtensionsTest.kt:26:21: Unexpected newline before "{"
.../extensions/AttributeExtensionsTest.kt:206:21: Unexpected newline before "{"
```

Our current workflow/usage is based on the assumption that these tools can be used together as mentioned in the kotlin-auto-formatter readme.
> It should be fine to use both ktlint and this formatter in the same project.

please let me know if I should clarify anything.
Kind Regards

**Comment by hovinen** [comment]
Hi Daniel,

Does the line beginning with `DynamicTest.dynamicTest` in the original version exceed the column limit?

If not, then it seems that there is indeed a bug, since the formatter then has no reason to break before the opening brace at the end of the line.

If it does exceed the column limit, then this is rather a bug in ktlint than in the auto-formatter. Namely, the following unavoidably requires moving the opening curly brace to the next line:

```
aFunctionCallWithAParticularlyLongNameWhichHitsTheColumnLimitAndASingleLambdaExpressionArgument
    { doSomething() }
```

But this is hard to distinguish from the variant with additional function arguments. Unfortunately there's not much the auto-formatter can do in this case, since it has to move the opening brace to the next line to fit things in the column limit.

If that is the case, my best suggestion would be to disable that particular ktlint check by adding

```
disabled_rules=curly-spacing
```

to your project's `.editorconfig` file.

**Comment by danielocallaghan** [comment]
Thanks Bradford for the info,
Indeed it looks to be the case that the original version hits the 100 column limit, the `)` character here is at 99:
```
                DynamicTest.dynamicTest("$attribute is an absence planned days attribute: $result") {
                    attribute.isAbsencePlannedDays() `should be equal to` result
                }  
```
I'll look into disabling the `curly-spacing` rule to unblock this compatibility issue.

Looks like it might be worth documenting/noting this for users that want to have both ktlint and this tool working together as this edge case could cause some confusion.

Thanks!

**Comment by hovinen** [comment]
Indeed, this should be documented. I'll add something as soon as I can.
